package com.lealex.alchymastery.client;

import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.util.Mth;
import net.minecraft.util.Util;

import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;

/**
 * Drawing helpers for the machines' themed GUIs (textures and positions generated by tools/gui_textures.py into
 * {@link GuiSprites}): the animated vignettes (a pot growing a flower, a hammer crushing ore...), the themed
 * progress arrow and flame, the glass overlays shaping the tanks, and light-on-dark labels.
 */
public final class GuiDecor {
    private GuiDecor() {}

    /**
     * An animated vignette: frames of w x h in textures/gui/{texture}.png, in a grid of {@code columns} per row, one
     * loop lasting {@code loopMillis} while the machine works, drawn at (x, y) in the screen.
     */
    public record Strip(String texture, int w, int h, int frames, int columns, int loopMillis, boolean holdWhenIdle, int x, int y) {
        public Identifier id() {
            return Identifier.fromNamespaceAndPath("alchymastery", "textures/gui/" + texture + ".png");
        }

        /** The texture's height: the frame grid, rounded up to a power of two (as the script saves it). */
        public int textureHeight() {
            int rows = (frames + columns - 1) / columns;
            return 1 << Math.max(4, 32 - Integer.numberOfLeadingZeros(rows * h - 1));
        }
    }

    /** Each vignette's phase in its loop (0 to 1) and when it was last drawn: it advances with real time. */
    private static final Map<Strip, double[]> PHASES = new IdentityHashMap<>();

    /**
     * Draws the current frame (left, top: the screen's corner). The phase follows real time (smooth at any tick rate
     * or frame rate); idle machines play at half speed, or (holdWhenIdle) finish the loop and rest on its first frame
     * (the hammer stays up).
     */
    public static void draw(GuiGraphicsExtractor graphics, Strip strip, int left, int top, boolean working) {
        long now = Util.getMillis();
        double[] state = PHASES.computeIfAbsent(strip, s -> new double[] {0, now});
        double elapsed = Math.min(100, Math.max(0, now - state[1])); // a closed screen doesn't jump ahead
        state[1] = now;
        double step = elapsed / strip.loopMillis();
        if (working) {
            state[0] = (state[0] + step) % 1.0;
        } else if (strip.holdWhenIdle()) {
            if (state[0] > 0) state[0] = state[0] + step >= 1.0 ? 0 : state[0] + step;
        } else {
            state[0] = (state[0] + step * 0.5) % 1.0;
        }
        int frame = Math.min(strip.frames() - 1, (int) (state[0] * strip.frames()));
        int u = (frame % strip.columns()) * strip.w(), v = (frame / strip.columns()) * strip.h();
        graphics.blit(RenderPipelines.GUI_TEXTURED, strip.id(), left + strip.x(), top + strip.y(), u, v, strip.w(), strip.h(), 256, strip.textureHeight());
    }

    /** The themed progress arrow, {@code width} pixels of it from the left (0 draws nothing). */
    public static void arrow(GuiGraphicsExtractor graphics, Identifier texture, GuiSprites.Sprite arrow, int x, int y, int width) {
        width = Math.min(width, arrow.w());
        if (width > 0) graphics.blit(RenderPipelines.GUI_TEXTURED, texture, x, y, arrow.u(), arrow.v(), width, arrow.h(), 256, 256);
    }

    /** The themed flame, burning down from the top as {@code fraction} goes from 1 to 0. */
    public static void flame(GuiGraphicsExtractor graphics, Identifier texture, GuiSprites.Sprite flame, int x, int y, float fraction) {
        if (fraction <= 0) return;
        int height = Math.min(flame.h(), Mth.ceil(Math.min(1.0F, fraction) * (flame.h() - 1)) + 1);
        int skip = flame.h() - height;
        graphics.blit(RenderPipelines.GUI_TEXTURED, texture, x, y + skip, flame.u(), flame.v() + skip, flame.w(), height, 256, 256);
    }

    /** The tanks' glass: drawn over the fluid fills, it shapes them as bottles, flasks, tubes or rods. */
    public static void overlays(GuiGraphicsExtractor graphics, Identifier texture, List<GuiSprites.Placed> overlays, int left, int top) {
        for (GuiSprites.Placed placed : overlays) {
            GuiSprites.Sprite s = placed.sprite();
            graphics.blit(RenderPipelines.GUI_TEXTURED, texture, left + placed.x(), top + placed.y(), s.u(), s.v(), s.w(), s.h(), 256, 256);
        }
    }

    /** The title and the inventory label in the theme's text color (vanilla's dark gray vanishes on dark panels). */
    public static void labels(GuiGraphicsExtractor graphics, Font font, Component title, int titleX, int titleY,
                              Component inventory, int inventoryX, int inventoryY, int color) {
        graphics.text(font, title, titleX, titleY, color, false);
        graphics.text(font, inventory, inventoryX, inventoryY, color, false);
    }
}
