package com.lealex.alchymastery.client;

// GENERATED by tools/gui_textures.py: don't edit, change the script and rerun it.

/** Sprite positions in the machines' GUI textures, their vignettes, and their text colors. */
public final class GuiSprites {
    private GuiSprites() {}

    /** A sprite in a GUI texture (u, v, size). */
    public record Sprite(int u, int v, int w, int h) {}

    /** A sprite drawn at (x, y) in the screen (relative to its top-left corner). */
    public record Placed(Sprite sprite, int x, int y) {}

    public static final Sprite MATRIX_FLAME = new Sprite(200, 0, 14, 14);
    public static final Sprite MATRIX_TANK_0 = new Sprite(0, 168, 90, 12);
    public static final java.util.List<Placed> MATRIX_OVERLAYS = java.util.List.of(new Placed(MATRIX_TANK_0, 79, 37));
    public static final int MATRIX_LABEL = 0xFFE6D8FF, MATRIX_OK = 0xFFC79AF0, MATRIX_BAD = 0xFFFF7A7A;
    public static final GuiDecor.Strip MATRIX_ANIM = new GuiDecor.Strip("distortion_matrix_anim", 32, 32, 48, 8, 2400, false, 10, 30);

    public static final Sprite DESTRUCTURATION_ARROW = new Sprite(176, 0, 24, 16);
    public static final java.util.List<Placed> DESTRUCTURATION_OVERLAYS = java.util.List.of();
    public static final int DESTRUCTURATION_LABEL = 0xFFF2DCCF, DESTRUCTURATION_OK = 0xFFFFB070, DESTRUCTURATION_BAD = 0xFFFF7A7A;
    public static final GuiDecor.Strip DESTRUCTURATION_ANIM = new GuiDecor.Strip("destructuration_anim", 40, 40, 36, 6, 1800, true, 8, 18);

    public static final Sprite TRANSMUTATION_ARROW = new Sprite(176, 0, 24, 16);
    public static final java.util.List<Placed> TRANSMUTATION_OVERLAYS = java.util.List.of();
    public static final int TRANSMUTATION_LABEL = 0xFFF2E4F0, TRANSMUTATION_OK = 0xFF7FE0D4, TRANSMUTATION_BAD = 0xFFFF8A8A;
    public static final GuiDecor.Strip TRANSMUTATION_ANIM = new GuiDecor.Strip("transmutation_anim", 28, 40, 48, 9, 3200, false, 140, 16);

    public static final Sprite CONDENSATOR_ARROW = new Sprite(176, 0, 24, 16);
    public static final Sprite CONDENSATOR_TANK_0 = new Sprite(0, 168, 20, 46);
    public static final Sprite CONDENSATOR_TANK_1 = new Sprite(20, 168, 20, 46);
    public static final java.util.List<Placed> CONDENSATOR_OVERLAYS = java.util.List.of(new Placed(CONDENSATOR_TANK_0, 51, 15), new Placed(CONDENSATOR_TANK_1, 105, 15));
    public static final int CONDENSATOR_LABEL = 0xFFD8F4F0, CONDENSATOR_OK = 0xFF9FE8E0, CONDENSATOR_BAD = 0xFFFF8A8A;
    public static final GuiDecor.Strip CONDENSATOR_ANIM = new GuiDecor.Strip("condensator_anim", 32, 52, 48, 8, 2400, false, 134, 14);

    public static final Sprite RECONSTRUCTION_ARROW = new Sprite(176, 0, 24, 16);
    public static final Sprite RECONSTRUCTION_TANK_0 = new Sprite(0, 168, 18, 54);
    public static final java.util.List<Placed> RECONSTRUCTION_OVERLAYS = java.util.List.of(new Placed(RECONSTRUCTION_TANK_0, 19, 16));
    public static final int RECONSTRUCTION_LABEL = 0xFF3A1E24, RECONSTRUCTION_OK = 0xFF6A2FB8, RECONSTRUCTION_BAD = 0xFFAA2222;
    public static final GuiDecor.Strip RECONSTRUCTION_ANIM = new GuiDecor.Strip("reconstruction_anim", 28, 44, 64, 9, 4000, false, 140, 14);

    public static final Sprite RENDERING_ARROW = new Sprite(176, 0, 24, 16);
    public static final Sprite RENDERING_TANK_0 = new Sprite(0, 168, 18, 54);
    public static final Sprite RENDERING_TANK_1 = new Sprite(18, 168, 18, 54);
    public static final java.util.List<Placed> RENDERING_OVERLAYS = java.util.List.of(new Placed(RENDERING_TANK_0, 19, 16), new Placed(RENDERING_TANK_1, 111, 16));
    public static final int RENDERING_LABEL = 0xFFEFE6C8, RENDERING_OK = 0xFFB8FF5A, RENDERING_BAD = 0xFFFF8A7A;
    public static final GuiDecor.Strip RENDERING_ANIM = new GuiDecor.Strip("rendering_anim", 30, 18, 40, 8, 2000, false, 80, 52);

    public static final Sprite ALCHEMICAL_NEXUS_ARROW = new Sprite(176, 0, 24, 16);
    public static final Sprite ALCHEMICAL_NEXUS_TANK_0 = new Sprite(0, 168, 18, 54);
    public static final Sprite ALCHEMICAL_NEXUS_TANK_1 = new Sprite(18, 168, 10, 54);
    public static final java.util.List<Placed> ALCHEMICAL_NEXUS_OVERLAYS = java.util.List.of(new Placed(ALCHEMICAL_NEXUS_TANK_0, 19, 16), new Placed(ALCHEMICAL_NEXUS_TANK_1, 153, 16));
    public static final int ALCHEMICAL_NEXUS_LABEL = 0xFFF4E6C0, ALCHEMICAL_NEXUS_OK = 0xFFFFD070, ALCHEMICAL_NEXUS_BAD = 0xFFFF7A7A;
    public static final GuiDecor.Strip ALCHEMICAL_NEXUS_ANIM = new GuiDecor.Strip("alchemical_nexus_anim", 12, 40, 48, 21, 2400, false, 140, 18);

    public static final Sprite EXPERIENCE_NEXUS_ARROW = new Sprite(176, 0, 24, 16);
    public static final Sprite EXPERIENCE_NEXUS_TANK_0 = new Sprite(0, 168, 18, 54);
    public static final Sprite EXPERIENCE_NEXUS_TANK_1 = new Sprite(18, 168, 10, 54);
    public static final Sprite EXPERIENCE_NEXUS_TANK_2 = new Sprite(28, 168, 18, 54);
    public static final java.util.List<Placed> EXPERIENCE_NEXUS_OVERLAYS = java.util.List.of(new Placed(EXPERIENCE_NEXUS_TANK_0, 13, 16), new Placed(EXPERIENCE_NEXUS_TANK_1, 33, 16), new Placed(EXPERIENCE_NEXUS_TANK_2, 109, 16));
    public static final int EXPERIENCE_NEXUS_LABEL = 0xFFD8F0EC, EXPERIENCE_NEXUS_OK = 0xFFB8FF5A, EXPERIENCE_NEXUS_BAD = 0xFFFF8A7A;
    public static final GuiDecor.Strip EXPERIENCE_NEXUS_ANIM = new GuiDecor.Strip("experience_nexus_anim", 36, 14, 32, 7, 1600, false, 133, 57);

}
